# Use an official Node runtime as a parent image
FROM node:latest as builder

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY swe642-assign3-frontend/package.json ./

# Install app dependencies
RUN npm install

# Bundle app source
COPY swe642-assign3-frontend/ ./

# Expose the port the app runs on
EXPOSE 4200

# Define the command to run your app
CMD ["npm", "start"]

