version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "8080:4200"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "8081:8080"
